"""Tests for laser_polio_nigeria.manifest, covering all three resolution paths."""
from pathlib import Path

import pytest

from laser_polio_nigeria.manifest import (
    EXPECTED_DATA_FILES,
    MissingDataError,
    _cli,
    load_manifest,
    write_manifest,
)


def _populate_data_files(target: Path):
    target.mkdir(parents=True, exist_ok=True)
    for filename in EXPECTED_DATA_FILES:
        (target / filename).write_bytes(b"")


def test_load_with_naked_dir(tmp_path, monkeypatch):
    """No manifest.py + a complete data dir => loader synthesizes all variables."""
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)

    mod = load_manifest()

    assert mod.DATA_ROOT == tmp_path
    for filename, var_name in EXPECTED_DATA_FILES.items():
        assert getattr(mod, var_name) == tmp_path / filename


def test_load_with_thin_manifest(tmp_path, monkeypatch):
    """manifest.py with only DATA_ROOT => loader fills in every other variable."""
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)
    (tmp_path / "manifest.py").write_text(
        "from pathlib import Path\n"
        "DATA_ROOT = Path(__file__).resolve().parent\n"
    )

    mod = load_manifest()

    assert mod.DATA_ROOT == tmp_path
    assert mod.population == tmp_path / "compiled_cbr_pop_ri_sia_underwt_africa.csv"
    assert mod.adjacency == tmp_path / "adm01_adjacency.npz"


def test_load_with_rich_manifest_backward_compatible(tmp_path, monkeypatch):
    """An old-style rich manifest that binds every variable still works.

    The loader should promote whatever the manifest defines and not overwrite
    those bindings with synthesized paths.
    """
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)
    custom_population = tmp_path / "i_overrode_population.csv"
    custom_population.write_bytes(b"")
    (tmp_path / "manifest.py").write_text(
        f"from pathlib import Path\n"
        f"DATA_ROOT = Path(__file__).resolve().parent\n"
        f"population = DATA_ROOT / 'i_overrode_population.csv'\n"
    )

    mod = load_manifest()

    assert mod.population == custom_population
    assert mod.adjacency == tmp_path / "adm01_adjacency.npz"


def test_load_raises_when_files_missing(tmp_path, monkeypatch):
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    victim = next(iter(EXPECTED_DATA_FILES))
    for filename in EXPECTED_DATA_FILES:
        if filename != victim:
            (tmp_path / filename).write_bytes(b"")

    with pytest.raises(MissingDataError) as exc:
        load_manifest()

    assert victim in str(exc.value)
    assert str(tmp_path) in str(exc.value)


def test_load_raises_when_dir_empty(tmp_path, monkeypatch):
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))

    with pytest.raises(MissingDataError, match="data not found"):
        load_manifest()


def test_write_manifest_produces_portable_manifest(tmp_path, monkeypatch):
    """A manifest.py generated by write_manifest must work after being moved."""
    origin = tmp_path / "origin"
    _populate_data_files(origin)
    write_manifest(origin)

    moved = tmp_path / "moved"
    origin.rename(moved)

    monkeypatch.setenv("LASER_POLIO_DATA", str(moved))
    mod = load_manifest()

    assert mod.DATA_ROOT == moved
    for filename, var_name in EXPECTED_DATA_FILES.items():
        assert getattr(mod, var_name) == moved / filename


def test_write_manifest_refuses_when_files_missing(tmp_path):
    victim = next(iter(EXPECTED_DATA_FILES))
    for filename in EXPECTED_DATA_FILES:
        if filename != victim:
            (tmp_path / filename).write_bytes(b"")

    with pytest.raises(MissingDataError, match="missing required files"):
        write_manifest(tmp_path)

    assert not (tmp_path / "manifest.py").exists()


def test_cli_writes_manifest(tmp_path, capsys):
    _populate_data_files(tmp_path)
    _cli([str(tmp_path)])

    assert (tmp_path / "manifest.py").exists()
    captured = capsys.readouterr()
    assert "manifest.py" in captured.out
