"""Tests for laser_polio_nigeria.manifest, covering all three resolution paths."""
from pathlib import Path

import pytest

from laser_polio_nigeria.manifest import (
    EXPECTED_DATA_FILES,
    MissingDataError,
    _cli,
    load_manifest,
    write_manifest,
)


def _populate_data_files(target: Path):
    target.mkdir(parents=True, exist_ok=True)
    for filename in EXPECTED_DATA_FILES:
        (target / filename).write_bytes(b"")


def test_load_with_naked_dir(tmp_path, monkeypatch):
    """No manifest.py + a complete data dir => loader synthesizes all variables."""
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)

    mod = load_manifest()

    assert mod.DATA_ROOT == tmp_path
    for filename, var_name in EXPECTED_DATA_FILES.items():
        assert getattr(mod, var_name) == tmp_path / filename


def test_load_with_thin_manifest(tmp_path, monkeypatch):
    """manifest.py with only DATA_ROOT => loader fills in every other variable."""
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)
    (tmp_path / "manifest.py").write_text(
        "from pathlib import Path\n"
        "DATA_ROOT = Path(__file__).resolve().parent\n"
    )

    mod = load_manifest()

    assert mod.DATA_ROOT == tmp_path
    assert mod.population == tmp_path / "compiled_cbr_pop_ri_sia_underwt_africa.csv"
    assert mod.adjacency == tmp_path / "adm01_adjacency.npz"


def test_load_with_rich_manifest_backward_compatible(tmp_path, monkeypatch):
    """An old-style rich manifest that binds every variable still works.

    The loader should promote whatever the manifest defines and not overwrite
    those bindings with synthesized paths.
    """
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)
    custom_population = tmp_path / "i_overrode_population.csv"
    custom_population.write_bytes(b"")
    (tmp_path / "manifest.py").write_text(
        f"from pathlib import Path\n"
        f"DATA_ROOT = Path(__file__).resolve().parent\n"
        f"population = DATA_ROOT / 'i_overrode_population.csv'\n"
    )

    mod = load_manifest()

    assert mod.population == custom_population
    assert mod.adjacency == tmp_path / "adm01_adjacency.npz"


def test_load_raises_when_files_missing(tmp_path, monkeypatch):
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    victim = next(iter(EXPECTED_DATA_FILES))
    for filename in EXPECTED_DATA_FILES:
        if filename != victim:
            (tmp_path / filename).write_bytes(b"")

    with pytest.raises(MissingDataError) as exc:
        load_manifest()

    assert victim in str(exc.value)
    assert str(tmp_path) in str(exc.value)


def test_load_raises_when_dir_empty(tmp_path, monkeypatch):
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))

    with pytest.raises(MissingDataError, match="data not found"):
        load_manifest()


def test_write_manifest_produces_portable_manifest(tmp_path, monkeypatch):
    """A manifest.py generated by write_manifest must work after being moved."""
    origin = tmp_path / "origin"
    _populate_data_files(origin)
    write_manifest(origin)

    moved = tmp_path / "moved"
    origin.rename(moved)

    monkeypatch.setenv("LASER_POLIO_DATA", str(moved))
    mod = load_manifest()

    assert mod.DATA_ROOT == moved
    for filename, var_name in EXPECTED_DATA_FILES.items():
        assert getattr(mod, var_name) == moved / filename


def test_write_manifest_refuses_when_files_missing(tmp_path):
    victim = next(iter(EXPECTED_DATA_FILES))
    for filename in EXPECTED_DATA_FILES:
        if filename != victim:
            (tmp_path / filename).write_bytes(b"")

    with pytest.raises(MissingDataError, match="missing required files"):
        write_manifest(tmp_path)

    assert not (tmp_path / "manifest.py").exists()


def test_load_coerces_string_data_root(tmp_path, monkeypatch):
    """A rich manifest that declares DATA_ROOT as a string (common in hand-written
    manifests) must work, not crash with a TypeError when the loader tries to do
    Path arithmetic."""
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)
    (tmp_path / "manifest.py").write_text(
        f"DATA_ROOT = {str(tmp_path)!r}\n"
    )

    mod = load_manifest()

    assert mod.DATA_ROOT == tmp_path
    assert mod.population == tmp_path / "compiled_cbr_pop_ri_sia_underwt_africa.csv"


def test_load_coerces_string_variable_paths(tmp_path, monkeypatch):
    """A manifest that binds a known variable to a str path must coerce to Path."""
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)
    (tmp_path / "manifest.py").write_text(
        f"from pathlib import Path\n"
        f"DATA_ROOT = Path({str(tmp_path)!r})\n"
        f"population = {str(tmp_path / 'compiled_cbr_pop_ri_sia_underwt_africa.csv')!r}\n"
    )

    mod = load_manifest()

    assert isinstance(mod.population, Path)
    assert mod.population == tmp_path / "compiled_cbr_pop_ri_sia_underwt_africa.csv"


def test_load_resolves_relative_string_data_root(tmp_path, monkeypatch):
    """A relative-string DATA_ROOT resolves against the manifest's directory,
    not against CWD."""
    nested = tmp_path / "nested"
    _populate_data_files(nested)
    (nested / "manifest.py").write_text("DATA_ROOT = '.'\n")

    monkeypatch.setenv("LASER_POLIO_DATA", str(nested))
    monkeypatch.chdir(tmp_path)  # CWD deliberately != nested

    mod = load_manifest()

    assert mod.DATA_ROOT == nested
    assert mod.population == nested / "compiled_cbr_pop_ri_sia_underwt_africa.csv"


def test_load_resolves_relative_string_variable_path(tmp_path, monkeypatch):
    """A relative-string variable resolves against DATA_ROOT, not against CWD."""
    _populate_data_files(tmp_path)
    (tmp_path / "manifest.py").write_text(
        f"from pathlib import Path\n"
        f"DATA_ROOT = Path({str(tmp_path)!r})\n"
        f"population = 'compiled_cbr_pop_ri_sia_underwt_africa.csv'\n"
    )

    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    monkeypatch.chdir(tmp_path.parent)  # CWD != DATA_ROOT

    mod = load_manifest()

    assert mod.population == tmp_path / "compiled_cbr_pop_ri_sia_underwt_africa.csv"


def test_load_processes_data_root_before_variable_bindings(tmp_path, monkeypatch):
    """If DATA_ROOT is declared *after* a variable in source order, the variable
    must still resolve against the correct DATA_ROOT (the manifest's, not the
    fallback)."""
    nested = tmp_path / "nested"
    _populate_data_files(nested)
    (nested / "manifest.py").write_text(
        # population declared FIRST, DATA_ROOT after — pure-string form.
        "population = 'compiled_cbr_pop_ri_sia_underwt_africa.csv'\n"
        "DATA_ROOT = '.'\n"
    )

    monkeypatch.setenv("LASER_POLIO_DATA", str(nested))
    monkeypatch.chdir(tmp_path)

    mod = load_manifest()

    assert mod.population == nested / "compiled_cbr_pop_ri_sia_underwt_africa.csv"


def test_load_falls_through_to_env_root_when_manifest_binding_is_stale(tmp_path, monkeypatch):
    """If a manifest binding points at a missing file but LASER_POLIO_DATA has the
    file under its default name, the loader uses the env-root version. The
    manifest is informational; LASER_POLIO_DATA is authoritative."""
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)
    (tmp_path / "manifest.py").write_text(
        f"from pathlib import Path\n"
        f"DATA_ROOT = Path(__file__).resolve().parent\n"
        f"population = DATA_ROOT / 'i-do-not-exist.csv'\n"
    )

    mod = load_manifest()

    # Manifest binding was unusable; loader fell through to <LASER_POLIO_DATA>/<filename>.
    assert mod.population == tmp_path / "compiled_cbr_pop_ri_sia_underwt_africa.csv"


def test_load_ignores_manifest_data_root_override(tmp_path, monkeypatch):
    """A manifest with a hardcoded DATA_ROOT pointing somewhere other than
    LASER_POLIO_DATA must NOT cause the loader to look at that other location.
    The env var is the user's stated intent — the manifest is just a hint."""
    env_root = tmp_path / "env_root"
    _populate_data_files(env_root)
    stale_root = tmp_path / "stale_root_with_no_files"
    stale_root.mkdir()

    (env_root / "manifest.py").write_text(
        f"from pathlib import Path\n"
        f"DATA_ROOT = Path({str(stale_root)!r})\n"
    )

    monkeypatch.setenv("LASER_POLIO_DATA", str(env_root))

    mod = load_manifest()

    assert mod.DATA_ROOT == env_root
    assert mod.population == env_root / "compiled_cbr_pop_ri_sia_underwt_africa.csv"


def test_load_error_message_surfaces_both_paths_when_they_disagree(tmp_path, monkeypatch):
    """If files are genuinely missing AND the manifest's DATA_ROOT disagrees with
    LASER_POLIO_DATA, the error message must mention both so the user isn't
    misdirected to fix the wrong location."""
    env_root = tmp_path / "env_root_empty"
    env_root.mkdir()
    stale_root = tmp_path / "the_old_dir"
    stale_root.mkdir()

    (env_root / "manifest.py").write_text(
        f"from pathlib import Path\n"
        f"DATA_ROOT = Path({str(stale_root)!r})\n"
    )

    monkeypatch.setenv("LASER_POLIO_DATA", str(env_root))

    with pytest.raises(MissingDataError) as exc:
        load_manifest()

    msg = str(exc.value)
    assert str(env_root) in msg
    assert str(stale_root) in msg
    assert "LASER_POLIO_DATA wins" in msg


def test_error_message_says_from_env_var_when_env_var_set(tmp_path, monkeypatch):
    """When LASER_POLIO_DATA is set, the missing-data error must NOT tell the
    user to 'set LASER_POLIO_DATA to override' — they already did. It should
    acknowledge the source ('from LASER_POLIO_DATA') so the user knows the
    loader is honoring their env var."""
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))

    with pytest.raises(MissingDataError) as exc:
        load_manifest()

    msg = str(exc.value)
    assert "(from LASER_POLIO_DATA)" in msg
    assert "(set LASER_POLIO_DATA to override)" not in msg


def test_error_message_says_set_env_var_when_unset(tmp_path, monkeypatch):
    """When LASER_POLIO_DATA is NOT set and the loader falls back to CWD, the
    error must hint that the user can set the env var to point elsewhere."""
    monkeypatch.delenv("LASER_POLIO_DATA", raising=False)
    monkeypatch.chdir(tmp_path)  # CWD becomes the unconfigured fallback root

    with pytest.raises(MissingDataError) as exc:
        load_manifest()

    msg = str(exc.value)
    assert "(set LASER_POLIO_DATA to override)" in msg
    assert "(from LASER_POLIO_DATA)" not in msg


def test_cli_writes_manifest(tmp_path, capsys):
    _populate_data_files(tmp_path)
    _cli([str(tmp_path)])

    assert (tmp_path / "manifest.py").exists()
    captured = capsys.readouterr()
    assert "manifest.py" in captured.out


def test_write_manifest_refuses_to_overwrite_existing_manifest(tmp_path):
    """A user-maintained manifest may contain custom overrides; clobbering it
    silently would risk data loss. write_manifest must refuse by default."""
    _populate_data_files(tmp_path)
    original = "# I am a hand-maintained manifest with custom logic\n"
    (tmp_path / "manifest.py").write_text(original)

    with pytest.raises(MissingDataError, match="already exists"):
        write_manifest(tmp_path)

    # The existing manifest must not have been touched.
    assert (tmp_path / "manifest.py").read_text() == original


def test_write_manifest_force_true_overwrites_existing(tmp_path):
    """force=True lets the caller knowingly replace an existing manifest."""
    _populate_data_files(tmp_path)
    (tmp_path / "manifest.py").write_text("# old content\n")

    target = write_manifest(tmp_path, force=True)

    assert target == tmp_path / "manifest.py"
    assert "old content" not in target.read_text()
    assert "Auto-generated" in target.read_text()


def test_cli_force_flag_overwrites(tmp_path, capsys):
    """The CLI exposes the force protection via --force."""
    _populate_data_files(tmp_path)
    (tmp_path / "manifest.py").write_text("# old content\n")

    # Without --force, the CLI surfaces the MissingDataError.
    with pytest.raises(MissingDataError, match="already exists"):
        _cli([str(tmp_path)])

    # With --force, the manifest is replaced.
    _cli([str(tmp_path), "--force"])
    assert "old content" not in (tmp_path / "manifest.py").read_text()


def test_write_manifest_rejects_nonexistent_path(tmp_path):
    """A typo'd path shouldn't surface as 'all 8 files are missing' — the
    actual problem is that the directory itself doesn't exist."""
    bogus = tmp_path / "this_path_does_not_exist"

    with pytest.raises(MissingDataError) as exc:
        write_manifest(bogus)

    msg = str(exc.value)
    assert "does not exist" in msg
    assert str(bogus) in msg
    # The misleading "missing required files" message must NOT appear.
    assert "missing required files" not in msg


def test_write_manifest_rejects_file_path(tmp_path):
    """If the user points write_manifest at a file (instead of a dir), say so
    plainly rather than falling through to the missing-files check."""
    bogus = tmp_path / "i_am_a_file.txt"
    bogus.write_bytes(b"")

    with pytest.raises(MissingDataError) as exc:
        write_manifest(bogus)

    msg = str(exc.value)
    assert "is a file" in msg
    assert str(bogus) in msg


def test_load_manifest_rejects_nonexistent_data_root(tmp_path, monkeypatch):
    """Typo'd LASER_POLIO_DATA surfaces as 'directory not found', not a wall of
    'missing files'."""
    bogus = tmp_path / "does_not_exist"
    monkeypatch.setenv("LASER_POLIO_DATA", str(bogus))

    with pytest.raises(MissingDataError) as exc:
        load_manifest()

    msg = str(exc.value)
    assert "directory not found" in msg
    assert "does not exist" in msg
    assert str(bogus) in msg


def test_load_manifest_rejects_file_as_data_root(tmp_path, monkeypatch):
    """Same defensive check when LASER_POLIO_DATA points at a file instead of
    a directory."""
    bogus = tmp_path / "a_file.txt"
    bogus.write_bytes(b"")
    monkeypatch.setenv("LASER_POLIO_DATA", str(bogus))

    with pytest.raises(MissingDataError) as exc:
        load_manifest()

    msg = str(exc.value)
    assert "is a file" in msg
    assert str(bogus) in msg


def test_load_manifest_wraps_exec_errors_in_missing_data_error(tmp_path, monkeypatch):
    """A manifest.py with a SyntaxError shouldn't bubble up an opaque exception
    from importlib — load_manifest must re-raise as MissingDataError with the
    underlying cause chained for context."""
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)
    (tmp_path / "manifest.py").write_text("this is not valid python (((\n")

    with pytest.raises(MissingDataError) as exc:
        load_manifest()

    msg = str(exc.value)
    assert "Failed to execute" in msg
    assert "manifest.py" in msg
    # The original exception is chained so a debugger / __cause__ inspection
    # still reaches it.
    assert exc.value.__cause__ is not None
