"""Tests for laser_polio_nigeria.manifest, covering all three resolution paths."""
from pathlib import Path

import pytest

from laser_polio_nigeria.manifest import (
    EXPECTED_DATA_FILES,
    MissingDataError,
    _cli,
    load_manifest,
    write_manifest,
)


def _populate_data_files(target: Path):
    target.mkdir(parents=True, exist_ok=True)
    for filename in EXPECTED_DATA_FILES:
        (target / filename).write_bytes(b"")


def test_load_with_naked_dir(tmp_path, monkeypatch):
    """No manifest.py + a complete data dir => loader synthesizes all variables."""
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)

    mod = load_manifest()

    assert mod.DATA_ROOT == tmp_path
    for filename, var_name in EXPECTED_DATA_FILES.items():
        assert getattr(mod, var_name) == tmp_path / filename


def test_load_with_thin_manifest(tmp_path, monkeypatch):
    """manifest.py with only DATA_ROOT => loader fills in every other variable."""
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)
    (tmp_path / "manifest.py").write_text(
        "from pathlib import Path\n"
        "DATA_ROOT = Path(__file__).resolve().parent\n"
    )

    mod = load_manifest()

    assert mod.DATA_ROOT == tmp_path
    assert mod.population == tmp_path / "compiled_cbr_pop_ri_sia_underwt_africa.csv"
    assert mod.adjacency == tmp_path / "adm01_adjacency.npz"


def test_load_with_rich_manifest_backward_compatible(tmp_path, monkeypatch):
    """An old-style rich manifest that binds every variable still works.

    The loader should promote whatever the manifest defines and not overwrite
    those bindings with synthesized paths.
    """
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)
    custom_population = tmp_path / "i_overrode_population.csv"
    custom_population.write_bytes(b"")
    (tmp_path / "manifest.py").write_text(
        f"from pathlib import Path\n"
        f"DATA_ROOT = Path(__file__).resolve().parent\n"
        f"population = DATA_ROOT / 'i_overrode_population.csv'\n"
    )

    mod = load_manifest()

    assert mod.population == custom_population
    assert mod.adjacency == tmp_path / "adm01_adjacency.npz"


def test_load_raises_when_files_missing(tmp_path, monkeypatch):
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    victim = next(iter(EXPECTED_DATA_FILES))
    for filename in EXPECTED_DATA_FILES:
        if filename != victim:
            (tmp_path / filename).write_bytes(b"")

    with pytest.raises(MissingDataError) as exc:
        load_manifest()

    assert victim in str(exc.value)
    assert str(tmp_path) in str(exc.value)


def test_load_raises_when_dir_empty(tmp_path, monkeypatch):
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))

    with pytest.raises(MissingDataError, match="data not found"):
        load_manifest()


def test_write_manifest_produces_portable_manifest(tmp_path, monkeypatch):
    """A manifest.py generated by write_manifest must work after being moved."""
    origin = tmp_path / "origin"
    _populate_data_files(origin)
    write_manifest(origin)

    moved = tmp_path / "moved"
    origin.rename(moved)

    monkeypatch.setenv("LASER_POLIO_DATA", str(moved))
    mod = load_manifest()

    assert mod.DATA_ROOT == moved
    for filename, var_name in EXPECTED_DATA_FILES.items():
        assert getattr(mod, var_name) == moved / filename


def test_write_manifest_refuses_when_files_missing(tmp_path):
    victim = next(iter(EXPECTED_DATA_FILES))
    for filename in EXPECTED_DATA_FILES:
        if filename != victim:
            (tmp_path / filename).write_bytes(b"")

    with pytest.raises(MissingDataError, match="missing required files"):
        write_manifest(tmp_path)

    assert not (tmp_path / "manifest.py").exists()


def test_load_coerces_string_data_root(tmp_path, monkeypatch):
    """A rich manifest that declares DATA_ROOT as a string (common in hand-written
    manifests) must work, not crash with a TypeError when the loader tries to do
    Path arithmetic."""
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)
    (tmp_path / "manifest.py").write_text(
        f"DATA_ROOT = {str(tmp_path)!r}\n"
    )

    mod = load_manifest()

    assert mod.DATA_ROOT == tmp_path
    assert mod.population == tmp_path / "compiled_cbr_pop_ri_sia_underwt_africa.csv"


def test_load_coerces_string_variable_paths(tmp_path, monkeypatch):
    """A manifest that binds a known variable to a str path must coerce to Path."""
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)
    (tmp_path / "manifest.py").write_text(
        f"from pathlib import Path\n"
        f"DATA_ROOT = Path({str(tmp_path)!r})\n"
        f"population = {str(tmp_path / 'compiled_cbr_pop_ri_sia_underwt_africa.csv')!r}\n"
    )

    mod = load_manifest()

    assert isinstance(mod.population, Path)
    assert mod.population == tmp_path / "compiled_cbr_pop_ri_sia_underwt_africa.csv"


def test_load_resolves_relative_string_data_root(tmp_path, monkeypatch):
    """A relative-string DATA_ROOT resolves against the manifest's directory,
    not against CWD."""
    nested = tmp_path / "nested"
    _populate_data_files(nested)
    (nested / "manifest.py").write_text("DATA_ROOT = '.'\n")

    monkeypatch.setenv("LASER_POLIO_DATA", str(nested))
    monkeypatch.chdir(tmp_path)  # CWD deliberately != nested

    mod = load_manifest()

    assert mod.DATA_ROOT == nested
    assert mod.population == nested / "compiled_cbr_pop_ri_sia_underwt_africa.csv"


def test_load_resolves_relative_string_variable_path(tmp_path, monkeypatch):
    """A relative-string variable resolves against DATA_ROOT, not against CWD."""
    _populate_data_files(tmp_path)
    (tmp_path / "manifest.py").write_text(
        f"from pathlib import Path\n"
        f"DATA_ROOT = Path({str(tmp_path)!r})\n"
        f"population = 'compiled_cbr_pop_ri_sia_underwt_africa.csv'\n"
    )

    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    monkeypatch.chdir(tmp_path.parent)  # CWD != DATA_ROOT

    mod = load_manifest()

    assert mod.population == tmp_path / "compiled_cbr_pop_ri_sia_underwt_africa.csv"


def test_load_processes_data_root_before_variable_bindings(tmp_path, monkeypatch):
    """If DATA_ROOT is declared *after* a variable in source order, the variable
    must still resolve against the correct DATA_ROOT (the manifest's, not the
    fallback)."""
    nested = tmp_path / "nested"
    _populate_data_files(nested)
    (nested / "manifest.py").write_text(
        # population declared FIRST, DATA_ROOT after — pure-string form.
        "population = 'compiled_cbr_pop_ri_sia_underwt_africa.csv'\n"
        "DATA_ROOT = '.'\n"
    )

    monkeypatch.setenv("LASER_POLIO_DATA", str(nested))
    monkeypatch.chdir(tmp_path)

    mod = load_manifest()

    assert mod.population == nested / "compiled_cbr_pop_ri_sia_underwt_africa.csv"


def test_load_validates_rich_manifest_paths_exist(tmp_path, monkeypatch):
    """A rich manifest must not silently hand the model paths to missing files."""
    monkeypatch.setenv("LASER_POLIO_DATA", str(tmp_path))
    _populate_data_files(tmp_path)
    (tmp_path / "manifest.py").write_text(
        f"from pathlib import Path\n"
        f"DATA_ROOT = Path(__file__).resolve().parent\n"
        f"population = DATA_ROOT / 'i-do-not-exist.csv'\n"
    )

    with pytest.raises(MissingDataError) as exc:
        load_manifest()

    assert "population" in str(exc.value)
    assert "i-do-not-exist.csv" in str(exc.value)


def test_cli_writes_manifest(tmp_path, capsys):
    _populate_data_files(tmp_path)
    _cli([str(tmp_path)])

    assert (tmp_path / "manifest.py").exists()
    captured = capsys.readouterr()
    assert "manifest.py" in captured.out
