# Auto-generated by nigeria_polio.bootstrap
# DO NOT EDIT BY HAND

from pathlib import Path

DATA_ROOT = Path('/home/jbloedow/LASER/laser-polio-nigeria/nigeria_polio_data')

def require(path: Path) -> Path:
    if not path.exists():
        raise FileNotFoundError(
            f"Missing data file: {path}\n"
            "Set LASER_POLIO_DATA to the correct location."
        )
    return path

adjacency = require(DATA_ROOT / 'adm01_adjacency.npz')
age_africa = require(DATA_ROOT / 'age_africa.csv')
age_pyramid = require(DATA_ROOT / 'Nigeria_age_pyramid_2024.csv')
cbr_nga = require(DATA_ROOT / 'cbr_NGA.json')
distance_matrix = require(DATA_ROOT / 'distance_matrix_africa_adm2.h5')
epi_20250408 = require(DATA_ROOT / 'epi_africa_20250408.h5')
epi_20260610 = require(DATA_ROOT / 'epi_africa_20260610.h5')
immunity_50 = require(DATA_ROOT / 'init_immunity_0.5coverage_january.h5')
immunity_80 = require(DATA_ROOT / 'init_immunity_0.8coverage_january.h5')
node_lookup = require(DATA_ROOT / 'node_lookup.json')
population = require(DATA_ROOT / 'compiled_cbr_pop_ri_sia_underwt_africa.csv')
regions = require(DATA_ROOT / 'regions.yaml')
seir_counts = require(DATA_ROOT / 'seir_counts_r0_200.csv')
shapefile = require(DATA_ROOT / 'shp_africa_low_res.gpkg')
sia_future = require(DATA_ROOT / 'sia_scenario_1.csv')
sia_historic = require(DATA_ROOT / 'sia_historic_schedule.csv')
synth_pop = require(DATA_ROOT / 'synth_data_nigeria_r014_k0.5.h5')

# Default initial immunity used by run_sim.py
init_immunity = immunity_50
