results_path: "results/response_sia_sweep_nigeria_0sia_response_sens0.8"
regions: ["NIGERIA"]
admin_level: 0
start_year: 2017
n_days: 2560
pop_scale: 1.0
vx_prob_ri: 0.0
init_region: "ANKA"
init_prev: 0
seed_schedule:
  - date: "2017-10-01"
    dot_name: "AFRO:NIGERIA:JIGAWA:HADEJIA"
    prevalence: 100
  - date: "2017-10-01"
    dot_name: "AFRO:NIGERIA:JIGAWA:GARKI"
    prevalence: 100
  - date: "2020-07-01"
    dot_name: "AFRO:NIGERIA:ZAMFARA:TALATA_MAFARA"
    prevalence: 100
  - date: "2020-10-01"
    dot_name: "AFRO:NIGERIA:NIGER:SULEJA"
    prevalence: 100
r0: 12.596628416809017
migration_method: "radiation"
radiation_k_log10: -1.9923605157363817
node_seeding_zero_inflation: 0.0
max_migr_frac: 0.05
seasonal_amplitude: 0.2346813621297781
seasonal_peak_doy: 200
use_pim_scalars: true
pim_re_center: -0.8426157363250124
pim_re_scale: 0.740827361594329
sia_schedule_source: "none"
paralysis_detection_sensitivity: 0.8
response_sia: true
response_sia_dist: 100
t_to_detect: 30
response_sia_time_to_1st_round: 30
response_sia_2nd_round_gap: 30
response_sia_blackout_duration: 182
response_sia_vaccine_type: "nOPV2"
response_sia_vaccine_strain: 2
response_sia_age_range: [0, 1825]
